# Generated by Django 3.0.3 on 2020-08-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='Coding', max_length=255),
            preserve_default=False,
        ),
    ]
